#ifndef ERROR_H
#define ERROR_H

#include <stdint.h>

enum
{
    ERROR_INVALID_SHOT_DATA_RECEIVED,
    ERROR_I2C_BUFFER_CONTENTION,
    ERROR_I2C_NO_ACK,
    ERROR_I2C_OUTGOING_QUEUE_FULL,
    ERROR_I2C_OUTGOING_QUEUE_EMPTY,
    ERROR_I2C_INCOMING_QUEUE_FULL,
    ERROR_I2C_UNEXPECTED_STATE,
    ERROR_LED_DRIVER_INVALID_REG_RANGE,
    ERROR_LED_DRIVER_TRANSMISSION_CONFLICT,
    ERROR_CIRCULAR_BUFFER_INDEX_OUT_OF_RANGE,
    ERROR_I2C_PARTIAL_WRITE_ADDRESS_MISMATCH,
    ERROR_I2C_ZERO_READ_LENGTH,
    ERROR_RECEIVED_TRANSMISSION_TOO_LONG
};

void fatal(uint8_t error_code);

#endif /* ERROR_H */
