#ifndef ERROR_H
#define	ERROR_H

#include <stdint.h>

enum
{
    ERROR_INVALID_SHOT_DATA_RECEIVED,
    ERROR_I2C_BUFFER_CONTENTION,
    ERROR_I2C_NO_ACK,
    ERROR_I2C_OUTGOING_QUEUE_FULL,
    ERROR_I2C_OUTGOING_QUEUE_EMPTY,
    ERROR_I2C_UNEXPECTED_STATE,
    ERROR_LED_DRIVER_INVALID_REG_RANGE,
    ERROR_LED_DRIVER_TRANSMISSION_CONFLICT
};

void fatal(uint8_t error_code);

#endif	/* ERROR_H */

