#ifndef ERROR_H
#define ERROR_H

#include <stdint.h>

enum
{
    // clang-format off
    ERROR_INVALID_SHOT_DATA_RECEIVED,
    ERROR_TRANSMISSION_TOO_LONG,
    ERROR_TRANSMISSION_OVERLAP,
    ERROR_UNHANDLED_PERIOD_MATCH,
    ERROR_UNHANDLED_PULSE_MEASUREMENT,
    ERROR_I2C_INCOMING_QUEUE_FULL,
    ERROR_I2C_OUTGOING_QUEUE_FULL,
    ERROR_I2C_OUTGOING_QUEUE_EMPTY,
    ERROR_I2C_UNEXPECTED_STATE,
    ERROR_PULSE_MEASUREMENT_DOESNT_FIT_SMT1,
    ERROR_GAP_MEASUREMENT_DOESNT_FIT_SMT1,
    ERROR_OVERLAPPING_PULSE_LENGTH_RANGES,
    ERROR_TRANSMISSION_GAP_LENGTH_DOESNT_FIT_TMR4,
    // clang-format on
};

void fatal(uint16_t error_code);

#endif /* ERROR_H */
